### PR TITLE
upgrade to latest v2

### PR DESCRIPTION
**Pull request by pnzrr**

### CODE REVIEW

**Comment by pnzrr** [comment]
/api/* pages are failing

**Comment by pnzrr** [comment]
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#compatibility-matrix

**Comment by xgp** [comment]
> https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#compatibility-matrix

Yeah, looks like we also have to upgrade to the `2.x.x (beta)` version of the plugin in order to upgrade Docusaurus.

**Comment by pnzrr** [comment]
Tried that, didn't work 😢

**Comment by xgp** [comment]
> Tried that, didn't work 😢

I've had some success with posting questions on the PANetworks plugin issues page. They are gruff and somewhat abusive, but they do actually try to help fairly quickly.

**Comment by pnzrr** [comment]
Yeah its under dev. Probably just wait a couple months to let them settle it a bit more before pursuing

**Pull request closed without merging**
