### PR TITLE
Update openapi for org members endpoint

### PR DESCRIPTION
**Pull request by kedare**
OpenAPI update related to https://github.com/p2-inc/keycloak-orgs/pull/244

### CODE REVIEW

**Review by pierre-tranchard — APPROVED** [review]

**Comment by pnzrr** [comment]
@xgp looks ok based on result of https://github.com/p2-inc/keycloak-orgs/pull/244

**Comment by pierre-tranchard** [comment]
@pnzrr @xgp is there anything remaining to do before you can merge it? Thank you in advance 🙏

**Comment by xgp** [comment]
@pierre-tranchard Yes. The feature itself in https://github.com/p2-inc/keycloak-orgs/pull/244 is no complete. Once it is, we can merge this.

**Comment by xgp** [comment]
Closing until it is possible to submit a completed PR for https://github.com/p2-inc/keycloak-orgs/pull/244

**Pull request closed without merging**
