### PR TITLE
Add additional frameworks

### PR DESCRIPTION
**Pull request by pnzrr**

### CODE REVIEW

**Comment by pnzrr** [comment]
@xgp I was having issues loading the pages as part of the hierarchy 

image
image

I feel like all you need to do is add the .md file and the front matter to that. Am I missing something?

**Comment by xgp** [comment]
@pnzrr The left menu gets built by the [sidebars.js](https://github.com/p2-inc/phasetwo-docs/blob/master/sidebars.js) file.

**Comment by pnzrr** [comment]
image

**Comment by pnzrr** [comment]
@xgp  good to go

**Review by xgp — APPROVED** [review]

**Pull request merged**
