### PR TITLE
[Draft] Template for Instant User Management and SSO for X (web framework)

### PR DESCRIPTION
**Pull request by pnzrr**
Partially Addresses #56 

Example Post
image
image

### CODE REVIEW

**Comment by xgp** [comment]
Sweet. Great starter. I think we can use this for all types.

**Comment by pnzrr** [comment]
image
image
image
image

**Comment by pnzrr** [comment]
Started example [repo](https://github.com/p2-inc/examples/tree/main)

**Comment by pnzrr** [comment]
Example template 
image

**Pull request merged**
